name: node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-tests-deploy
    runs-on: ubuntu-latest

  steps:
  - name: checkout
    uses: actions/checkout@v2
  - name: set up node.js
    uses: actions/setup-node@v4
    with:
      node-version: '14'
    
    

